[package]
name = "crawler"
version = "0.1.0"
edition = "2024"

[dependencies]
fetcher = { path = "../fetcher" }
parser = { path = "../parser" }
storage = { path = "../storage" }
tokio = { version = "1", features = ["full"] }
